### ISSUE TITLE
Add fields to Variable model (currently only in the search index)

### ISSUE THREAD

**Issue by afuetterer** [ddionrails/ddionrails#466]
### Fields

- [x] statistics -> JSONField
- [x] categories vs.
- ~uni ?~
- [x] scale

TODO:
- [x] fix broken test case in tests/functional/test_imports.py
- [x] make sure visualization has access to categories

**Comment by afuetterer** [comment]
<http://localhost:9200/dor/variable/1?format=yaml>

```yaml
---
_index: "dor"
_type: "variable"
_id: "1"
_version: 1
found: true
_source:
  study: "soep-core"
  name: "hhnr"
  name_cs: "hhnr"
  variable: "hhnr"
  dataset: "abroad"
  label: "Original Household Number"
  categories:
    frequencies: []
    labels: []
    missings: []
    values: []
    labels_de: []
  statistics:
    names:
    - "Min."
    - "1st Qu."
    - "Median"
    - "Mean"
    - "3rd Qu."
    - "Max."
    - "valid"
    - "invalid"
    values:
    - "230"
    - "56944"
    - "286486"
    - "386593.084848485"
    - "515230"
    - "3107360"
    - "165"
    - "0"
  scale: ""
  analysis_unit: "p"
  sub_type: "tl-org/net"
  boost: null
  period: "0"
  label_de: "Ursprungshaushaltsnummer"
  namespace: "soep-core"
  uni:
    frequencies: []
    labels: []
    missings: []
    values: []
    labels_de: []
```

**Comment by afuetterer** [comment]
<http://localhost:9200/dor/variable/1000?format=yaml>

```yaml
---
_index: "dor"
_type: "variable"
_id: "1000"
_version: 1
found: true
_source:
  study: "soep-core"
  name: "ap1d004"
  name_cs: "ap1d004"
  variable: "ap1d004"
  dataset: "apkal"
  label: "Officially Unemployed Apr Prev Yr"
  categories:
    frequencies:
    - 0
    - 0
    - 0
    - 0
    - 11834
    - 0
    - 456
    labels:
    - "[-6] Version of questionnaire with modified filtering"
    - "[-5] Not included in this version of the questionnaire"
    - "[-4] Inadmissible multiple response"
    - "[-3] Answer improbable"
    - "[-2] Does not apply"
    - "[-1] No Answer"
    - "[1] Yes"
    missings:
    - true
    - true
    - true
    - true
    - true
    - true
    - false
    values:
    - "-6"
    - "-5"
    - "-4"
    - "-3"
    - "-2"
    - "-1"
    - "1"
    labels_de:
    - "[-6] Fragebogenversion mit geaenderter Filterfuehrung"
    - "[-5] In Fragebogenversion nicht enthalten"
    - "[-4] Unzulaessige Mehrfachantwort"
    - "[-3] nicht valide"
    - "[-2] trifft nicht zu"
    - "[-1] keine Angabe"
    - "[1] Ja"
  statistics:
    names:
    - "valid"
    - "invalid"
    values:
    - "456"
    - "11834"
  scale: "cat"
  analysis_unit: "p"
  sub_type: "raw-gen"
  boost: null
  period: "1984"
  label_de: "Arbeitslos gemeldet    Apr 1983"
  namespace: "soep-core"
  uni:
    frequencies:
    - 0
    - 0
    - 0
    - 0
    - 11834
    - 0
    - 456
    labels:
    - "[-6] Version of questionnaire with modified filtering"
    - "[-5] Not included in this version of the questionnaire"
    - "[-4] Inadmissible multiple response"
    - "[-3] Answer improbable"
    - "[-2] Does not apply"
    - "[-1] No Answer"
    - "[1] Yes"
    missings:
    - true
    - true
    - true
    - true
    - true
    - true
    - false
    values:
    - "-6"
    - "-5"
    - "-4"
    - "-3"
    - "-2"
    - "-1"
    - "1"
    labels_de:
    - "[-6] Fragebogenversion mit geaenderter Filterfuehrung"
    - "[-5] In Fragebogenversion nicht enthalten"
    - "[-4] Unzulaessige Mehrfachantwort"
    - "[-3] nicht valide"
    - "[-2] trifft nicht zu"
    - "[-1] keine Angabe"
    - "[1] Ja"
```

**Comment by afuetterer** [comment]
https://github.com/ddionrails/ddionrails/blob/64ce732438c08b232d11658104cdf271a3aecb7a/ddionrails/data/models/variable.py#L173-L181

**Comment by afuetterer** [comment]
@hansendx How to store statistics?

1.
```python
statistics = {
  "names": ["valid", "invalid"],
  "values": [1, 0]
}
```

2.
```python
statistics = [
  {"name": "valid", "value": 1},
  {"name": "invalid", "value": 0}
]
```

3.
```python
statistics = {
  "valid": 1,
  "invalid": 0
}
```

**Comment by afuetterer** [comment]
uni vs. categories

https://github.com/ddionrails/ddionrails/blob/959c03da048b19da8575a2b4c4f5940b58f84616/ddionrails/data/models/variable.py#L145-L148

https://github.com/ddionrails/ddionrails/blob/959c03da048b19da8575a2b4c4f5940b58f84616/ddionrails/data/models/variable.py#L154-L171

**Comment by hansendx** [comment]
I would prefer Nr. 3

**Comment by afuetterer** [comment]
@hansendx How to store categories?

1. 
```python
categories = {
  "frequencies": [0, 1],
  "labels": [
    "[-6] Version of questionnaire with modified filtering",
    "[1] Yes"
  ],
  "missings": [true, false]
  "values": ["-6", 1],
  "labels_de": [
    "[-6] Fragebogenversion mit geaenderter Filterfuehrung,
    "[1] Ja"
  ],
}
```

2.
```python
categories = [
{
  "value": "-6",
  "label": "[-6] Version of questionnaire with modified filtering",
  "frequency": 0,
  "valid": false
},
{
  "value": "1",
  "label": "[1] Yes",
  "frequency": 1,
  "valid": true
}
]
```

**Comment by afuetterer** [comment]
http://localhost:9200/dor/

see "dor.mappings.variable":

```yaml
variable:
      properties:
        analysis_unit:
          type: "string"
        categories:
          properties:
            frequencies:
              type: "long"
            labels:
              type: "string"
            labels_de:
              type: "string"
            missings:
              type: "boolean"
            values:
              type: "string"
        dataset:
          type: "string"
        label:
          type: "string"
        label_de:
          type: "string"
        name:
          type: "string"
        name_cs:
          type: "string"
        namespace:
          type: "string"
        period:
          type: "string"
        scale:
          type: "string"
        statistics:
          properties:
            names:
              type: "string"
            values:
              type: "string"
        study:
          type: "string"
        sub_type:
          type: "string"
        uni:
          properties:
            frequencies:
              type: "long"
            labels:
              type: "string"
            labels_de:
              type: "string"
            missings:
              type: "boolean"
            values:
              type: "string"
        variable:
          type: "string"
```
