### ISSUE TITLE
Add fields to Question model (currently only in the search index)

### ISSUE THREAD

**Issue by afuetterer** [ddionrails/ddionrails#467]
<http://localhost:9200/dor?format=yaml>

see "dor.mappings.question":

```yaml
 question:
      properties:
        analysis_unit:
          type: "string"
          fields:
            raw:
              type: "string"
              index: "not_analyzed"
        instrument:
          type: "string"
        items:
          properties:
            answer_list:
              type: "string"
            answers:
              properties:
                label:
                  type: "string"
                label_de:
                  type: "string"
                value:
                  type: "long"
            concept:
              type: "string"
            description:
              type: "string"
            filter:
              type: "string"
            goto:
              type: "string"
            instruction:
              type: "string"
            instruction_de:
              type: "string"
            item:
              type: "string"
            number:
              type: "string"
            scale:
              type: "string"
            sn:
              type: "long"
            text:
              type: "string"
            text_de:
              type: "string"
        label:
          type: "string"
        name:
          type: "string"
          fields:
            raw:
              type: "string"
              index: "not_analyzed"
        namespace:
          type: "string"
        period:
          type: "string"
          fields:
            raw:
              type: "string"
              index: "not_analyzed"
        question:
          type: "string"
        sn:
          type: "long"
        study:
          type: "string"
          fields:
            raw:
              type: "string"
              index: "not_analyzed"
        sub_type:
          type: "string"
          fields:
            raw:
              type: "string"
              index: "not_analyzed"
```

Items is an Array of JSON objects.
